name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
          - py38-dj32-wag216
          - py38-dj32-wag30
          - py38-dj40-wag216
          - py38-dj40-wag30
          - py310-dj32-wag216
          - py310-dj32-wag30
          - py310-dj40-wag216
          - py310-dj40-wag30
        include:
          - toxenv: py38-dj32-wag216
            python-version: "3.8"
          - toxenv: py38-dj32-wag30
            python-version: "3.8"
          - toxenv: py38-dj40-wag216
            python-version: "3.8"
          - toxenv: py38-dj40-wag30
            python-version: "3.8"
          - toxenv: py310-dj32-wag216
            python-version: "3.10"
          - toxenv: py310-dj32-wag30
            python-version: "3.10"
          - toxenv: py310-dj40-wag216
            python-version: "3.10"
          - toxenv: py310-dj40-wag30
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
            tox
            coveralls
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
